//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunScan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Last Scan Ran: Never")]
        public string lastScanRunTime {
            get {
                return ((string)(this["lastScanRunTime"]));
            }
            set {
                this["lastScanRunTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<SunScan.Classes.aDevice> favoritesList {
            get {
                return ((global::System.Collections.Generic.List<SunScan.Classes.aDevice>)(this["favoritesList"]));
            }
            set {
                this["favoritesList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overwriteIP {
            get {
                return ((bool)(this["overwriteIP"]));
            }
            set {
                this["overwriteIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ipToOverwrite {
            get {
                return ((string)(this["ipToOverwrite"]));
            }
            set {
                this["ipToOverwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ipScanRange {
            get {
                return ((int)(this["ipScanRange"]));
            }
            set {
                this["ipScanRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Network")]
        public string ipToScan {
            get {
                return ((string)(this["ipToScan"]));
            }
            set {
                this["ipToScan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nmap -p 135 -oX - ")]
        public string nmapCommand {
            get {
                return ((string)(this["nmapCommand"]));
            }
            set {
                this["nmapCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool windowNotLocked {
            get {
                return ((bool)(this["windowNotLocked"]));
            }
            set {
                this["windowNotLocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoriteManufacturer {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoriteManufacturer"]));
            }
            set {
                this["favoriteManufacturer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoriteIP {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoriteIP"]));
            }
            set {
                this["favoriteIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoriteMAC {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoriteMAC"]));
            }
            set {
                this["favoriteMAC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoriteWMI {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoriteWMI"]));
            }
            set {
                this["favoriteWMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wmiIPScan {
            get {
                return ((string)(this["wmiIPScan"]));
            }
            set {
                this["wmiIPScan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultWMIUsername {
            get {
                return ((string)(this["defaultWMIUsername"]));
            }
            set {
                this["defaultWMIUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultWMIPassword {
            get {
                return ((string)(this["defaultWMIPassword"]));
            }
            set {
                this["defaultWMIPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultWMIDomain {
            get {
                return ((string)(this["defaultWMIDomain"]));
            }
            set {
                this["defaultWMIDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool scanForPCName {
            get {
                return ((bool)(this["scanForPCName"]));
            }
            set {
                this["scanForPCName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useSystemDNS {
            get {
                return ((bool)(this["useSystemDNS"]));
            }
            set {
                this["useSystemDNS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoritePCName {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoritePCName"]));
            }
            set {
                this["favoritePCName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoritePCManufacturer {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoritePCManufacturer"]));
            }
            set {
                this["favoritePCManufacturer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoritePCModel {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoritePCModel"]));
            }
            set {
                this["favoritePCModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoritePCUser {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoritePCUser"]));
            }
            set {
                this["favoritePCUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoritePCOS {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoritePCOS"]));
            }
            set {
                this["favoritePCOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> favoritePCType {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["favoritePCType"]));
            }
            set {
                this["favoritePCType"] = value;
            }
        }
    }
}
